### ISSUE TITLE
need new

### ISSUE THREAD

**Issue by Sakuraelf** [Seraphli/RoR2ShareItemMod#2]
The game has been updated new dlc,the previous method has not worked.Can you update the method if you have free time？thanks.

**Comment by Seraphli** [comment]
I have done some modification, but need more tests. I will upload a new version later on.

**Comment by Seraphli** [comment]
Check out the new version. Tested.

**Comment by Sakuraelf** [comment]
> Check out the new version. Tested.

ok，thanks
